### ISSUE TITLE
README getting started yarn/node version

### ISSUE THREAD

**Issue by ascasson** [ascasson/super-duper-job-board#10]
Users should have Node v8 or higher installed. Users can also run the app with the `yarn install` and `yarn start` commands. This information should be added to the readme.

**Comment by rasfa98** [comment]
I can fix this 😄

**Comment by ascasson** [comment]
@rasfa98 It's all yours, good sir! Thank you!

**Comment by goelrohan6** [comment]
@ascasson fixed it #13

**Comment by goelrohan6** [comment]
@ascasson can you review it

**Comment by ascasson** [comment]
@goelrohan6 Thanks! Because I already gave @rasfa98 👍 to do the task, I'm going to wait for his contribution unless he wants to let it go to you. I'm curious what both of you come up with :)

**Comment by ascasson** [comment]
Thanks to both of you! Plenty other issues available, and more to come.
