### ISSUE TITLE
Add CSS Modules compatibility 

### ISSUE THREAD

**Issue by ascasson** [ascasson/super-duper-job-board#32]
The React app needs to have webpack configurated to allow for CSS modules

**Comment by jacekk** [comment]
@ascasson R U sure it needs webpack? --> https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-modules-stylesheet .

**Comment by ascasson** [comment]
@jacekk Create React App uses Webpack built in. But it looks like all it needs is the .module.css extension? hmmm handy
