### ISSUE TITLE
Dev: Eslint, linting config (AirBnB)

### ISSUE THREAD

**Issue by ascasson** [ascasson/super-duper-job-board#37]
To help define better code rules, adding **eslint**, and **eslint-config-airbnb** to the project will give the workflow a helping hand. (Note: I'm open to other eslint configs if another might be suggested)

**Comment by mithwick93** [comment]
@ascasson I have experience in integrating `eslint` with the required `config` files. We can add https://prettier.io/ as well to have a standard code style and add `pre-commit` hooks as well. May I take this task?

**Comment by ascasson** [comment]
@mithwick93 Absolutely - that sounds great! Much appreciated 😃

**Comment by mithwick93** [comment]
@ascasson  I will start working on this right away
