### ISSUE TITLE
Add job board footer component

### ISSUE THREAD

**Issue by ascasson** [ascasson/super-duper-job-board#5]
Our app needs a footer. It can be open for interpretation here. Perhaps it could use a placeholder image and some general styling. Have fun with it!

**Comment by kemonrider** [comment]
HI @ascasson , I just created PR #30 to add basic footer. The footer just contain a placeholder image and links, it can be updated later. Hope it helps.

**Comment by ascasson** [comment]
@kemonrider Thank you so much! That's awesome! And I really appreciate the README additions as well. 👍
