### ISSUE TITLE
README update: "How to run the app"

### ISSUE THREAD

**Issue by ascasson** [ascasson/super-duper-job-board#6]
We need a section in the README that tells people how to get started by running the app.

**Comment by ascasson** [comment]
@iamgrawal It's all yours! I'll label it as in-progress. Thanks a bunch!

**Comment by iamgrawal** [comment]
@ascasson I created the PR, see if you need more changes.

**Comment by ascasson** [comment]
@iamgrawal You're all set! I merged it already :)

**Comment by iamgrawal** [comment]
@ascasson I think you should close this issue now 😃

**Comment by ascasson** [comment]
@iamgrawal see above! 👍
